### ISSUE TITLE
SourceTV doesn't toggle correctly

### ISSUE THREAD

**Issue by bauxiteDYS** [Rainyan/sourcemod-nt-competitive#42]
SourceTV doesn't end recording after a competitive match is finished.

**Comment by Rainyan** [comment]
Does this only happen when the match incorrectly goes live again (does the "LIVE LIVE LIVE" print, etc) right after concluding, or is this a separate bug from it?

**Comment by bauxiteDYS** [comment]
Separate bug, I think I've found out why it goes live again incorrectly.

**Comment by bauxiteDYS** [comment]
I think I've fixed both issues, just need to test it in a pug soon. ;0
